name: Detect Secrets

on: [push, pull_request]

jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install detect-secrets
        run: pip install detect-secrets
      - name: Run detect-secrets
        run: detect-secrets scan
